# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - graphviz
    - python3-catkin-pkg
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx doc/source"

python:
  install:
    - requirements: doc/requirements.txt
#    - method: pip
#      path: .
#      extra_requirements:
#      - catkin_pkg
#      - sphinx

sphinx:
  builder: html
  # Path to your Sphinx configuration file.
  configuration: doc/source/conf.py
